language: android
android:
  components:
  - platform-tools
  - tools
  - android-28
  - build-tools-28.0.2
  - extra-android-support
  - extra-android-m2repository
  licenses:
  - android-sdk-license-.+
jdk:
- oraclejdk8
branches:
  except:
  - gh-pages
notifications:
  email: false
sudo: false
script: "./gradlew :library:build :library:test :sample:assembleDebug :sample:testDebug"
cache:
  directories:
  - "$HOME/.gradle"
  - "$HOME/.m2"
env:
  global:
  - secure: onEexL+D+rhQKj6/0s2ySkc0+Xpvul6ZRGTA0slZfE1caZx8Gp2g3vanYmI69ZqRmJIQFeUsOTZQxYwWrv2eAWSUXtPhCCdgnpY5duaOiVCB2uHSZYtp4hTkW94V/N2kyjnD0BkylwJzU6XlSpsmXXwd7LRSnPUmsZPFgYiIm3B53Ww57RGLwaBz2EZDGt0ExHDZ4NlIjZAcUr6bdIzpVVoYLX21dChxYOalHMzmdk4L6aWTWVG/Cxoa+MzBNAg6p7HPmnVj23lq+RR0fHJY2Xr3PevNtBUhiVjS494IEnr5b9h2MT47PDwDEymKGd9cFaQF8x4h0Tj3gAAUEUrkzz3dRDZ7jc3qADBK95Zr4krGuCiUgkQ8yzk+FQpHfhiNspHD0td8PxmDy3cdxdn9/Hn474JQW0PBYot3gJpDTEs5OYQMDhE+Ier/gGgVyFbybj8bp7nRUYga3F1Ac9wlHoqmFy+Do8dG7canseBtkZxKx1WanDbKDEHiWq+e0IJyd66kh1ma/J91fp+HC2/zZaqSISboK/dbERrzWFtJu7S7dmIhXhJWOgizRqXzsGnoEhd5wSaZENLoaY0PqDH6x/kZi+bsT1vOVUhjIL3P9yHbbBxnLOEjEON2AQN12dI80TtvJDp6OEIYPJRzT3giH9KYA/33VgDKcbGCuCVLd4w=
  - secure: e8EMMFo6yEjLVASjcg+4pPRzzzANnSm7Jdv//gVS3IrCcVfdIN39g+CinYls9Aew4NpbXGjE7K/0BTjY0o1p+W6Q9z79mwrQOEk8JNKOznDrn4iXo78pZk+mCjgwLsc0ptStWCowxsJMR61bqBpseENfk8POo8tdehy7X/qQ4XN5Q4M6/5Oup9KfqijWN7ZCdLg6wDhs0iNJKor9epR7D4V34aqQOURXlNWKWBs7gAU2GU86/BL61TCGqRvnRvtTfY6RFUNwB9BQi/xVkXdb+T3yO72Af/rglDKbnpQWvuSB1QL6tY5MKFSJCWjulANzFjqtwLJaC8z2hP2nEpEONdQBZKEmNbrXcib7Lgk42YpF2zreNzm3+QyHBFsIfK7tWf4ev2TQ0w/qaU5g654akr/2ue2YwMZMNM0TCmMAV0tOWKFyA3t7+tftzhTSVHKOD6O2MySVeDGdCrM18SbkmH4BvfLCt5tp9/85OxJYCanbNwpyCqoi70wCl2Izy6pd0LtwT+thluEAoOz56ZLhaoCd9e3tsmUg918W70Q9l/aCbr6w9KW4qF1+zBNTdfAAxMEFAqgU+EKIuzPIGTSdcz7mMmIWTkobRy8KB5IotcfrXovnis622HuKQ/O8a9NpOEOC1s/sen0bQgSJyCmGRzmjkhtdQJk4GJaNXKe5Q3c=
  - secure: sX+5o0SKd+D/hqgwvuqzdXYcPJzhedmsjHy5kat/jJlJPAOMRndtoHpBLPOP35JkcmYgg6jH411suF/jSI4onhP5vcp+cMW77WenT6JwTcMtTXglg02I0X5orlpEwb4PzHRIGhZVClrYh40OOtNl5wgDX0d3COUsmCGrd2ZETAONU2W8gkUPY7jmRvwuHwDE8b/Y4T4UELktgNg9dFNttujE4ikEa5TUbZ/OCDOYCQy9WVj6nqcolfseQKGHXYWxpPjMmKJFuMTL7qQFC7ZQSXi7lXkdAjMtCb/tQ4TvDIgLkZZwVmQpw40SOQCm6WFHDRBBNwvQYVrEC9Lh9H1pPRfktb4EGJSE6FNC5/K6ZHV20PKyMkUhA/v12/G46RT/ZmqeuPZAvp7Z6sNYn7fLF/6dPYH2+l0DPSIEYxYauoD00AR0EmXqw+ghrONuVdLcpUIi7TLBCFjoXKmED4J3LfR+1ZTtpCsZQw/l4YH7xkT0cED9QkKTWYuQJtDqX0oCLYdz3C9v1OxA+1g+JHD+MDQUPyUyoegFp3KKkPCxyZyiezhVZ1tGpnvHiVG8rpdGhLJlT4Ve+1fCCFBVUjyNVrjg5i+fVN0Pm3kPpWI8Hzz3a7gnKHDchebmdAISFqgIOXcapgToDitE4lDTD7sJQ/6ZrPqGsebZdNSiFv4KJlg=
after_success:
- "./deploy.sh"

