version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "dependencies.gradle" }}-{{ checksum  "dependencies.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: dependencies-{{ checksum "dependencies.gradle" }}-{{ checksum  "dependencies.gradle" }}
  deploy_snapshot:
  branches:
      only:
        - master
  steps:
    - run:
      name: "Setup signing key"
      command: |
        openssl aes-256-cbc -d -a -in .circleci/Freeletics.asc.enc -out signingkey.asc -pass pass:$DECRYPTION_KEY
        gpg --import signingkey.asc --passphrase $PGP_KEY
        rm signingkey.asc
        gpg --list-keys


    - run:
        name: "Deploy snapshot or release"
        command: echo "Done"
