ersion: 2
jobs:
  build:
   docker:
        - image: circleci/android:api-27-alpha
      envoronment:
        JVM_OPTS: -Xmx3200m
      steps:
        - checkout
        - restore_cache:
            key: gradle-cache-{{ checksum "dependencies.gradle" }}

        - run:
            name: "Install signing key"
            command: gpg --list-keys

        - save_cache:
              paths:
                - ~/.gradle
              key: gradle-cache-{{ checksum "dependencies.gradle" }}
